version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - angular-app
      - angular-server
      - mongo-express
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/localhost.crt:/etc/nginx/ssl/certs/localhost.crt
      - ./ssl/localhost.key:/etc/nginx/ssl/private/localhost.key
    networks:
      - frontend
      - mongo-network

  angular-app:
    container_name: angular-app
    image: angular-app:latest
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - angular-server
    networks:
      - frontend

  angular-server:
    container_name: angular-server
    image: angular-server:latest
    restart: always
    volumes:
      - ./ssl:/usr/src/app/ssl
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - frontend
      - backend

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - backend
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_SITE_SSL_ENABLED=true
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_SITE_SSL_CRT_PATH=/localhost.crt
      - ME_CONFIG_SITE_SSL_KEY_PATH=/localhost.key
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - ./ssl/localhost.crt:/localhost.crt
      - ./ssl/localhost.key:/localhost.key
    networks:
      - mongo-network


volumes:
  mongodata:


networks:
  backend:
    driver: bridge
  frontend:
  mongo-network:
