apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: kube-angular-app:latest
        ports:
        - containerPort: 4200
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  type: LoadBalancer
  selector:
    app: angular-app
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
    nodePort: 32000
