apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
data:
  environment.ts: |
    {
      "production": true,
      "apiUrl": "https://angular-server-service:3000"
    }
  environment.development.ts: |
    {
      "production": false,
      "apiUrl": "http://angular-server-service:3000"
    }
