apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-config
data:
  localhost.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQDj+5j2DG1rMz
    C13nLVHs0a9HaULO0mNQbZQ3418hny8d+X55OleWx6R4HUoRII5dYVcFx+s6dG+U
    gL00bIrxHSV1jToyBZ/j32pHaygY6kg02uff0DyFKBuF4GzoCx8xD8R5udEwrp+L
    PrSB4ivKUHt262/ksZw3Xw/osaopsUnIBA6VobDvpOI8w1Z5fRGXH4w9+CjfVCsl
    d3LfPKoU1MCs3GbdrxHbqRxGQqknWpTBVKkUpP12q5z9h7XMlbatUAeLpB+hymnn
    2hYRz3c6/vgi+8T+dZFIGikfyk/Qelb7JkEqrOm7P2hz3DYWsLqNxye7SUzMI7RF
    /Vguh1zZAgMBAAECggEAD0z3oMTg6sk//9ar1DmAAeOLJBGjU88jIKITuWcjnYxg
    YbBHKHvYPy11dKPqyNxVEUb8UwotzBcOBvokxVCKM0s1Gwevf52W8aIs5bhasuJf
    5wsw7EPF1PZrImsBIgYssrtPHrNB+suMzie8DKU+b9rVXvHXlmuoFREM/CGSEGNo
    TaLVrbJWL5f5a+wNwPON2xE4660FAYkPpu0lD531ASeXH+bstkUKyjch92X1tNc9
    GeFy7lQ+xBxc92r4OvHCOe6BjH0ObMmwsxRhealZImvHv5JStvOYsHmt2ezpbbnd
    dSQykhu2S4en5nmV3Voyx+W3E6NuPflmzNoIGKxJVQKBgQD8eh/XcOnL3eulOJbf
    oCfsHShN6rdhbvQYl47JWcbBsy17MIrA9MRE6BcF3kGsuwhRToHV5D/m6jkdYVLv
    7ggF9rYU5XvYUNQFPf1Xr2gUOVEVgNSiNIP5HPTcm6C3Yid6zP+Bng9hClfuyaR5
    a68Fle7gD7YXUUA9r0cPymBINwKBgQDS9XJNCMdXCqILLntOIGukbOUqxC4id68Z
    Q+loD12eWZVo4zyigAbXr1Iyh4XpT+PAH1l7uCGt38LgStqebTkM2Z5rYZ+m4TNu
    xIowq2Bi5Rb+Bb20JuW7t4LM9A3wUj7KULr002dRGfg8qdZ7VseOS3nJ2xGl+a1M
    FSv45IfbbwKBgEkqWu/kGNyrgw5uR8qmbutNx9BMpLfnn3VA9nADREX91sBMYOlq
    BTayy3k333BfAxoM1jNV4e7ZEZQiEBbXtBuGU13a4vjc85RRUomGm3LA6W6B1xzq
    exRF/++uafS6zRYZMjIty+cjSDg61x8Yxa+os4DbDLnVIfi+QqmgzCYhAoGAX2sr
    jxJ4b7Nchig5F6ZsacvjgAuKPobaCViBW1MP6k7k2LNnuqyj66zeRgKsnFJJVp4X
    cHFhsm6yi5bv+Za3pktMb4+Rkf7sr55wTwFFMJYkZzObkb/CS7z+icud/mSFCCep
    2JFCexl/AZlkbRdcXc1fweC3w9YB/5bX89USajsCgYEAhwGjwWxJCp/+mXJrSGKz
    Jwe+l985GtKe9mAC9tfIY8U7Ptne0FgDWjWcaypWvIRH5WZ7t2e7/S3CqP1NoVmo
    bY8CUIQudUDTjOdnIr9QuyIuTsSP5fbjh4KjnmDzeBrWaRR1upvwEmP4AMj5+4gd
    NTn8aWJMAWZKU1XcFSdOMvk=
    -----END PRIVATE KEY-----
  localhost.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDmjCCAoKgAwIBAgIUObJ7jvFBgvedMbOoXwEnpP2eDaswDQYJKoZIhvcNAQEL
    BQAwIjELMAkGA1UEBhMCVVMxEzARBgNVBAMMCk15LVJvb3QtQ0EwHhcNMjQwODMw
    MDMwNTM2WhcNMjcwNjIwMDMwNTM2WjBtMQswCQYDVQQGEwJVUzESMBAGA1UECAwJ
    WW91clN0YXRlMREwDwYDVQQHDAhZb3VyQ2l0eTEdMBsGA1UECgwURXhhbXBsZS1D
    ZXJ0aWZpY2F0ZXMxGDAWBgNVBAMMD2xvY2FsaG9zdC5sb2NhbDCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBANAOP7mPYMbWszMLXectUezRr0dpQs7SY1Bt
    lDfjXyGfLx35fnk6V5bHpHgdShEgjl1hVwXH6zp0b5SAvTRsivEdJXWNOjIFn+Pf
    akdrKBjqSDTa59/QPIUoG4XgbOgLHzEPxHm50TCun4s+tIHiK8pQe3brb+SxnDdf
    D+ixqimxScgEDpWhsO+k4jzDVnl9EZcfjD34KN9UKyV3ct88qhTUwKzcZt2vEdup
    HEZCqSdalMFUqRSk/XarnP2HtcyVtq1QB4ukH6HKaefaFhHPdzr++CL7xP51kUga
    KR/KT9B6VvsmQSqs6bs/aHPcNhawuo3HJ7tJTMwjtEX9WC6HXNkCAwEAAaN9MHsw
    HwYDVR0jBBgwFoAUCBLkT+cXhoRW0qwsHHdsh8eIISQwCQYDVR0TBAIwADALBgNV
    HQ8EBAMCBPAwIQYDVR0RBBowGIIJbG9jYWxob3N0ggtmYWtlMS5sb2NhbDAdBgNV
    HQ4EFgQUUfuztgVlLtmXD/CzbYlLZFJxTfYwDQYJKoZIhvcNAQELBQADggEBABar
    BO85zj2L4O8oeG/e04Pz2GVyEtxlJEKLGQib9rNeV2tvFlskvEK1Aix/jPZu9cbM
    O3+z9dXVTH2U/+NEL2UGsnoLBJDlkza5hm1q1XmVb9FX9IfnhJbxVUWYfKn6WrII
    DKwJp0WxGhWplpG0tVAFsdpwbHA+IPU/f78yhm01hcJp+wcQj8kZbvzJdPjV5UcB
    E19hpQ9dL20/VYJTdQErpzI728zjo5+0dc0kDKmOWqaDTZI40ku5kfiA4AI2TMRl
    br5ZVXWCvL5gymz8RJec18yTwwYQf7+2Kez1Xpmsh4t/Yp3iLZwvsdqvRMbGBrby
    rXC9tFCLt8Q8bJk2Z+E=
    -----END CERTIFICATE-----
